// Generated by tools/generate_mobile_snapshot_types.py; do not edit.
use serde::{Deserialize, Serialize};

pub type Label = String;
pub type OpaqueId = String;
pub type Decimal = String;
pub type Sequence = String;
pub type Date = String;
pub type Month = String;
pub type UtcTimestamp = String;
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct Availability {
    pub state: String,
    pub reason: Option<Label>,
}
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct Sections {
    pub overview: Availability,
    pub accounts: Availability,
    pub investments: Availability,
    pub budgets: Availability,
    pub reports: Availability,
    pub comparisons: Availability,
    pub calculators: Availability,
}
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct Profile {
    pub id: OpaqueId,
    pub name: Label,
    pub icon: Option<Label>,
}
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct Overview {
    pub net_worth: Decimal,
    pub cash: Decimal,
    pub debt_contribution: Decimal,
    pub investments: Decimal,
    pub other_accounts: Decimal,
    pub property_value: Decimal,
    pub property_valued_from: Option<Date>,
    pub property_valued_through: Option<Date>,
    pub average_monthly_spend: Option<Decimal>,
    pub runway_months: Option<Decimal>,
}
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct Account {
    pub id: OpaqueId,
    pub name: Label,
    pub account_type: String,
    pub balance: Decimal,
    pub starting_balance: Decimal,
    pub net_worth_contribution: Decimal,
    pub owed: Option<Decimal>,
    pub balance_basis: String,
    pub checkpoint_date: Option<Date>,
    pub member_id: Option<OpaqueId>,
    pub icon: Option<Label>,
}
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct Member {
    pub id: OpaqueId,
    pub name: Label,
}
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct QuoteCoverage {
    pub state: String,
    pub valued_positions: u32,
    pub total_positions: u32,
    pub quote_timestamp: Option<UtcTimestamp>,
    pub previous_close_date: Option<Date>,
}
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct InvestmentSummary {
    pub account_id: OpaqueId,
    pub value: Decimal,
    pub cost_basis: Option<Decimal>,
    pub unrealized_gain: Option<Decimal>,
    pub day_change: Option<Decimal>,
    pub coverage: QuoteCoverage,
}
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct Investments {
    pub value: Decimal,
    pub cost_basis: Option<Decimal>,
    pub unrealized_gain: Option<Decimal>,
    pub day_change: Option<Decimal>,
    pub coverage: QuoteCoverage,
    pub accounts: Vec<InvestmentSummary>,
}
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct BudgetLine {
    pub category: Label,
    pub group: String,
    pub order: u32,
    pub planned: Decimal,
    pub actual: Decimal,
    pub rollover: Decimal,
    pub effective_budget: Decimal,
    pub remaining: Decimal,
    pub cap_enabled: bool,
    pub rollover_enabled: bool,
    pub alert: String,
}
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct BudgetMonth {
    pub month: Month,
    pub actual_through: Option<Date>,
    pub source_month: Option<Month>,
    pub cap_feature_enabled: bool,
    pub rollover_feature_enabled: bool,
    pub lines: Vec<BudgetLine>,
    pub unbudgeted_spending: Decimal,
    pub actual_income: Decimal,
    pub actual_spending: Decimal,
}
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct MonthTotals {
    pub month: Month,
    pub income: Decimal,
    pub spending: Decimal,
    pub savings_rate_pct: Option<Decimal>,
}
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct CategoryMonth {
    pub month: Month,
    pub category: Label,
    pub group: Option<String>,
    pub spending: Decimal,
}
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct BudgetCategoryMonth {
    pub month: Month,
    pub category: Label,
    pub signed_amount: Decimal,
}
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct DailySpend {
    pub date: Date,
    pub spending: Decimal,
}
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct MonthBreakdown {
    pub month: Month,
    pub id: Option<OpaqueId>,
    pub label: Label,
    pub income: Decimal,
    pub spending: Decimal,
}
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct NetWorthPoint {
    pub date: Date,
    pub net_worth: Decimal,
    pub cash: Decimal,
    pub debt_contribution: Decimal,
    pub investments: Decimal,
    pub property_value: Decimal,
    pub valuation_basis: String,
}
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct ValuePoint {
    pub date: Date,
    pub value: Decimal,
}
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct MemberWorth {
    pub member_id: Option<OpaqueId>,
    pub label: Label,
    pub value: Decimal,
}
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct History {
    pub from_month: Option<Month>,
    pub through_month: Option<Month>,
    pub actual_through: Date,
    pub months: Vec<MonthTotals>,
    pub categories: Vec<CategoryMonth>,
    pub budget_category_net: Vec<BudgetCategoryMonth>,
    pub daily: Vec<DailySpend>,
    pub accounts: Vec<MonthBreakdown>,
    pub members: Vec<MonthBreakdown>,
    pub tags: Vec<MonthBreakdown>,
    pub merchants: Vec<MonthBreakdown>,
    pub net_worth: Vec<NetWorthPoint>,
    pub portfolio: Vec<ValuePoint>,
    pub member_net_worth: Vec<MemberWorth>,
}
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct DollarBasis {
    pub kind: String,
    pub period: Label,
}
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct ComparisonReference {
    pub id: Label,
    pub mode: String,
    pub definition_id: Label,
    pub value: Decimal,
    pub adjusted_value: Decimal,
    pub uncertainty: Option<Decimal>,
    pub uncertainty_kind: Option<String>,
    pub unit: String,
    pub statistic: String,
    pub population: Label,
    pub universe: String,
    pub geography: Label,
    pub age_min: u32,
    pub age_max: Option<u32>,
    pub period_kind: String,
    pub period_from: Date,
    pub period_to: Date,
    pub dollar_basis: DollarBasis,
    pub adjusted_basis_month: Month,
    pub cpi_factor: Decimal,
    pub source_id: Label,
    pub source_url: Label,
    pub source_locator: Label,
    pub annotation: Option<Label>,
    pub reliability: String,
}
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct ComparisonReason {
    pub code: Label,
    pub detail: Option<Label>,
    pub options: Vec<Label>,
}
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct ComparisonResult {
    pub metric: String,
    pub status: String,
    pub local_value: Option<Decimal>,
    pub reference: Option<ComparisonReference>,
    pub dollar_difference: Option<Decimal>,
    pub percent_difference: Option<Decimal>,
    pub completeness: String,
    pub reasons: Vec<ComparisonReason>,
}
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct ComparisonContributor {
    pub label: Label,
    pub gross: Decimal,
    pub share_basis_points: u32,
    pub counted: Decimal,
}
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct ComparisonClass {
    pub label: Label,
    pub value: Decimal,
}
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct ComparisonSecondary {
    pub label: Label,
    pub result: ComparisonResult,
}
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct ComparisonCard {
    pub result: ComparisonResult,
    pub visible: bool,
    pub definition_id: Option<Label>,
    pub stale: bool,
    pub personal_income_hint: bool,
    pub metric_unit: String,
    pub period_kind: Option<String>,
    pub period_from: Option<Date>,
    pub period_to: Option<Date>,
    pub origin: String,
    pub measured_on: Option<Date>,
    pub explanation: Option<Label>,
    pub unallocated: Decimal,
    pub tracked_value: Option<Decimal>,
    pub contributors: Vec<ComparisonContributor>,
    pub excluded: Vec<ComparisonReason>,
    pub class_totals: Vec<ComparisonClass>,
    pub notes: Vec<ComparisonReason>,
    pub secondary: Vec<ComparisonSecondary>,
}
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct Comparisons {
    pub configured: bool,
    pub package_version: Option<Label>,
    pub setup_revision: Sequence,
    pub problem: Option<Label>,
    pub cards: Vec<ComparisonCard>,
}
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct ContributionMonth {
    pub month: Month,
    pub money_in: Decimal,
    pub money_out: Decimal,
}
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct AccumulationPlan {
    pub monthly_contribution: Option<Decimal>,
    pub annual_return_pct: Decimal,
    pub withdraw_month: Option<Month>,
    pub withdraw_years: Option<u32>,
}
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct Accumulation {
    pub account_id: OpaqueId,
    pub months: Vec<ContributionMonth>,
    pub total_in: Decimal,
    pub total_out: Decimal,
    pub net: Decimal,
    pub first_deposit: Option<Date>,
    pub deposit_count: u32,
    pub plan: AccumulationPlan,
    pub value_history: Vec<ValuePoint>,
}
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct DebtInput {
    pub account_id: OpaqueId,
    pub owed: Decimal,
    pub annual_rate_pct: Option<Decimal>,
    pub excluded: bool,
}
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct ScheduledFlow {
    pub date: Date,
    pub money_in: Decimal,
    pub money_out: Decimal,
}
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct Forecast {
    pub through_date: Date,
    pub start_balance: Decimal,
    pub trend_daily_net: Decimal,
    pub everyday_daily_net: Decimal,
    pub uses_recurring: bool,
    pub schedule: Vec<ScheduledFlow>,
}
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct GoalSummary {
    pub id: OpaqueId,
    pub name: Label,
    pub target: Option<Decimal>,
    pub saved: Decimal,
    pub target_date: Option<Date>,
    pub monthly_contribution: Option<Decimal>,
    pub monthly_pace: Decimal,
    pub tracks_account: bool,
    pub linked_account_id: Option<OpaqueId>,
    pub member_id: Option<OpaqueId>,
}
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct RecurringSummary {
    pub monthly_income: Decimal,
    pub monthly_expense: Decimal,
    pub annual_income: Decimal,
    pub annual_expense: Decimal,
}
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct Calculators {
    pub inflation_pct: Decimal,
    pub accumulation: Vec<Accumulation>,
    pub debts: Vec<DebtInput>,
    pub forecast: Forecast,
    pub goals: Vec<GoalSummary>,
    pub recurring: RecurringSummary,
}
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct MobileSnapshotV1 {
    pub schema_version: u32,
    pub minimum_viewer_version: u32,
    pub installation_id: OpaqueId,
    pub profile: Profile,
    pub epoch: OpaqueId,
    pub sequence: Sequence,
    pub generated_at: UtcTimestamp,
    pub as_of_date: Date,
    pub currency: String,
    pub sections: Sections,
    pub members: Vec<Member>,
    pub overview: Overview,
    pub accounts: Vec<Account>,
    pub investments: Investments,
    pub budgets: Vec<BudgetMonth>,
    pub history: History,
    pub comparisons: Comparisons,
    pub calculators: Calculators,
}
