import type { Account, Transaction } from "./types";

/** Shared account-type grouping — used anywhere accounts are organized by
 * kind (Accounts/Reports tabs' account sections, the debt payoff planner,
 * the Transactions tab's account filter), so "what counts as Cash vs. Credit vs.
 * Loan" lives in exactly one place. */
export const GROUP_ORDER = ["cash", "credit", "loan", "investment", "other"] as const;
export type AccountGroup = (typeof GROUP_ORDER)[number];
export const GROUP_LABELS: Record<AccountGroup, string> = {
  cash: "Cash",
  credit: "Credit Cards",
  loan: "Loans",
  investment: "Investments",
  other: "Other Assets",
};

export function groupOf(accountType: string): AccountGroup {
  if (accountType === "checking" || accountType === "savings") return "cash";
  if (accountType === "credit") return "credit";
  if (accountType === "loan") return "loan";
  if (accountType === "investment") return "investment";
  return "other";
}

/** A credit account's `starting_balance` is a limit — owed starts at $0,
 * so only the change since then (current_balance - starting_balance)
 * counts. A loan's `starting_balance` is the amount already owed, so the
 * whole thing counts as debt from the start, same as a fresh cash
 * account's balance counts in full — just negative. Shared between
 * AccountsView (its own assets/liabilities/net-worth stats) and
 * ReportsView (net worth by family member). */
export function netWorthContribution(a: Account): number {
  const group = groupOf(a.account_type);
  if (group === "credit") {
    return parseFloat(a.current_balance) - parseFloat(a.starting_balance);
  }
  if (group === "loan") {
    return -parseFloat(a.current_balance);
  }
  return parseFloat(a.current_balance);
}

/** How much is actually owed on a debt account, as a positive number —
 * the inverse framing of `netWorthContribution` (which is negative-signed
 * for debt), used anywhere a debt is listed as a plain balance rather than
 * netted into a total (the debt payoff planner, and its condensed
 * Dashboard summary). */
export function owedAmount(a: Account): number {
  const group = groupOf(a.account_type);
  if (group === "loan") return parseFloat(a.current_balance);
  return parseFloat(a.starting_balance) - parseFloat(a.current_balance);
}

/** Whether a transaction counts as real income — a positive amount that
 * isn't money moving between the household's own accounts (Transfer) or
 * a credit/loan account's own balance-side entry (a refund/credit there
 * reduces what's owed; it was never earned). Mirrors `Store::monthly_totals`
 * on the backend exactly (Cash Flow's own income figure), so every other
 * income figure in the app — Reports' "Income (all-time)" stat and Savings
 * Rate Trend, Ask the Vault's "income" queries — agrees with what Cash
 * Flow shows instead of quietly re-deriving its own answer. Deliberately
 * does *not* require the category be literally "Income": a paycheck
 * categorized "Salary," "Paycheck," or anything else still counts, since
 * that's what Cash Flow already does — a transaction never generated by
 * `apply_debt_payment` reaches the frontend at all (`all_transactions`
 * excludes it), so unlike the backend query this needs no id-based
 * exclusion for that case. An `account_id` missing from `accounts` (should
 * never happen — a transaction's account is never hard-deleted out from
 * under it) is treated as "not credit/loan" rather than excluded, so a
 * caller that only cares about other transactions and passes a partial or
 * empty `accounts` list isn't forced to also supply every account. */
export function isIncomeTransaction(t: Pick<Transaction, "amount" | "category" | "account_id">, accounts: Account[]): boolean {
  if (parseFloat(t.amount) <= 0) return false;
  if (t.category === "Transfer") return false;
  const account = accounts.find((a) => a.id === t.account_id);
  if (!account) return true;
  const group = groupOf(account.account_type);
  return group !== "credit" && group !== "loan";
}

/** Whether a transaction dated `date` on `account` is at or before that
 * account's last balance checkpoint — a monthly rollover or a manual
 * "correct balance" (see `Store::account_balance_as_of` on the backend,
 * which reads `checkpoint_date` as `since_date`). A checkpoint's own value
 * already accounts for everything through its date, so a transaction dated
 * on or before it can't move `current_balance` — it still correctly
 * affects past "balance as of" lookups (sparklines, net worth history),
 * just not today's live number. Used by `NewTransactionDialog` to warn
 * before that's a silent surprise. */
export function isBeforeAccountCheckpoint(account: Pick<Account, "checkpoint_date">, date: string): boolean {
  return account.checkpoint_date !== null && date !== "" && date <= account.checkpoint_date;
}
