/** One entry per released version — shown once via `WhatsNewDialog` when
 * the installed version differs from what this viewer last saw (tracked in
 * localStorage by App.tsx). Bundled locally rather than fetched from
 * GitHub, so it works fully offline like the rest of the app. Add an entry
 * here as part of cutting each release, condensed from that release's
 * GitHub notes — a version with no entry here just shows nothing. */
export const CHANGELOG: Record<string, string[]> = {
  "1.1.2": [
    "Ledger columns are now sortable — click a header to sort by it, click again to flip direction.",
    "The Ledger's account filter is now a dropdown grouped by account type, with a checkbox per account so you can filter to several at once.",
    "\"Add to Recurring\" — select transactions in the Ledger and turn them directly into recurring items.",
    "Fixed the Dashboard's budget-alerts breakdown showing the wrong categories as over budget.",
  ],
  "1.1.3": [
    "A banner now lets you know when a newer version is available to download, checked once each time you open the app.",
    "The current version now shows in the sidebar, above the theme toggle.",
    "A \"What's new\" summary now appears once per version, whether you just installed for the first time or just updated.",
  ],
  "1.1.4": [
    "Family members — tag any account, transaction, bucket, asset, or recurring item with who it belongs to, then filter the Ledger down to just one person. Manage them from the Ledger tab.",
    "Profiles — add completely separate, independent profiles (their own accounts, transactions, everything) for genuinely separate finances, switchable anytime from the sidebar indicator.",
    "Optional live stock prices for Investments — add a free Alpha Vantage API key in Settings to auto-fill a new holding's price by symbol and keep existing ones current automatically, with a usage tracker that warns you before you hit Alpha Vantage's daily request limit.",
    "The Help page now has a search box that filters the whole page at once as it keeps growing.",
  ],
  "1.1.5": [
    "\"Update now\" downloads the right installer for your system and opens it directly, instead of just linking to GitHub.",
    "Add a transaction to the Ledger by hand — no file import required.",
    "The Ledger's filters are decluttered — Search/Category/Account/Member stay visible, date range and tags now collapse into a \"More filters\" button.",
    "The Dashboard's recent transactions, upcoming bills, and budget summary now click through to the relevant tab.",
    "Cash Flow is now split into Overview / Forecast / Debt Payoff tabs instead of one long scrolling page.",
    "Smaller polish: a \"Due soon\" badge on upcoming recurring bills, labeled fields on the Investments \"Add holding\" form, and a clearer note distinguishing family members from profiles.",
  ],
  "1.1.6": [
    "Bulk-import investment holdings — \"Holdings\" is now a 5th section on the setup-data template (Reports tab), so you can add many stocks at once instead of one at a time.",
    "Two more live-price providers alongside Alpha Vantage: Finnhub (60 requests/minute, no daily cap) and Twelve Data (800 requests/day) — pick whichever fits your portfolio in Settings.",
    "Fixed an account's balance sometimes not reflecting a transaction added the same day its monthly balance rolled forward, until the next day.",
    "Fixed a payment applied to a credit card, loan, or mortgage counting twice — once as the real payment and again as an extra expense in Budget, Cash Flow, and category totals.",
  ],
  "1.1.7": [
    "The sidebar is now organized into groups — Overview, Money, Planning, Insights — with Settings and Help pinned below.",
    "Accounts is now its own page, split out of Reports, with its own Assets/Liabilities/Net Worth stats.",
    "The Ledger's toolbar is decluttered — Manage categories, Manage family members, Categorize uncategorized, and Export CSV now live behind a \"⋯\" menu.",
    "Budget now shows group-summary cards up top, and each budget line has its own progress bar alongside its budgeted/actual/remaining amounts.",
    "The Dashboard's Net Worth/Cash/Debt/Investments cards now show a trend sparkline and a 6-month change; its spending-by-category donut (and Cash Flow's matching one) now shows the total spent in the center.",
    "Recurring now has an Account column, and Suggested items are shown as cards instead of a table.",
    "Settings → Profiles: \"Use existing file…\" points Vault Spend at a vaultspend.db copied over from another computer, instead of only ever starting a new profile empty.",
    "Exporting the Ledger to CSV and re-importing that same file now actually preserves category, tags, and account — including creating any account that doesn't exist yet — instead of losing that data.",
    "Fixed \"Update now\" silently failing to open the downloaded installer.",
    "Fixed a debt payment applied to a credit card, loan, or mortgage still inflating Budget, Cash Flow, and category totals in a few more places the 1.1.6 fix missed.",
    "Smaller fixes: splitting a transaction now shows the split editor under the row you clicked instead of at the bottom of the table, the Dashboard's Upcoming Bills rows line up in two proper columns, and Budget's category dropdowns line up in a straight column.",
  ],
  "1.1.8": [
    "Success, error, and in-progress messages now look different from each other — color, icon, and a dismiss button — instead of one identical line for everything; errors stay up longer since they're more worth actually reading.",
    "Delete confirmations across the app (accounts, transactions, budget lines, recurring items, holdings, buckets, categories, family members, and profiles) now auto-cancel if left alone for a few seconds, and use a clearly different-colored button instead of a same-looking relabeled one.",
    "Dashboard's budget alerts now show the most-over-budget category first, instead of in whatever order categories happen to be listed.",
    "Every dialog can now be closed with Escape, and the sidebar's drag-to-reorder now also works from the keyboard — focus a tab and press Alt+↑/↓.",
    "Fixed the sidebar's group labels (\"OVERVIEW\", \"MONEY\", …) getting clipped instead of hiding when the window is narrow.",
  ],
  "1.1.9": [
    "A first-run checklist on the Dashboard walks new setups through adding an account, a transaction, and a budget, then gets out of the way.",
    "The Dashboard now shows a runway stat — how many months your liquid savings would cover at your recent average spend.",
    "Add Transaction now shows a live \"$X of $Y used\" line for the selected category's budget, and actually flags a non-numeric amount before you can save it.",
    "Flexible Spending categories on the Budget page now show a small trend sparkline of the last few months' actual spend.",
    "Recurring has a new Calendar view alongside the list, laying bills out on an actual month grid.",
    "Buckets' \"+ New bucket\" is now an in-grid tile instead of a separate button below the grid.",
    "The Ledger can save named filter combinations as chips for one-click reuse, and bulk-deleting transactions now shows an \"Undo\" toast instead of deleting immediately.",
    "Modals, the \"More\" menu, and expandable stat panels now animate open and closed; respects your OS's reduced-motion setting.",
    "StockData.org is now available as a live stock-price provider in Settings (100 requests/day, batches of up to 3 symbols per request).",
  ],
  "1.1.10": [
    "Investments now shows a \"Today's gain/loss\" figure, portfolio-wide and per-holding, based on the last price update of the day.",
    "Settings now has a permanent Release Notes section so you can look back at what changed in any past version, not just the one you just updated to.",
    "Fixed bill due-date checks and CSV export filenames occasionally landing on the wrong day depending on your timezone.",
    "Fixed switching or creating a profile occasionally losing track of which database file it was pointed at.",
    "Add Transaction, new holdings, and new assets now reject invalid or negative amounts instead of silently accepting them and corrupting totals.",
    "Contrast, keyboard, and screen-reader polish across the app: darker text and accent colors for readability, in-app messages that no longer shift the page when they appear, sparklines and filter checkboxes that expose their meaning to screen readers, and the Recurring calendar now shows each bill's amount directly instead of hiding it behind a tooltip.",
  ],
  "1.2.0": [
    "Accounts: click the balance (or amount owed) to correct it directly — it becomes the exact number you type immediately, already accounting for anything on the ledger that day, and new transactions still adjust it normally from there.",
    "Credit cards: the limit is now edited separately from the amount owed — click \"Available\" to change the limit, click \"Owed\" to correct what's owed directly.",
    "Deleting a transaction now shows exactly how much — and which direction — it'll change the account's balance before you confirm.",
    "The Ledger's date and description can now be corrected after the fact, alongside the amount, account, member, and category.",
  ],
  "1.2.1": [
    "Sinking funds: a bucket can now auto-contribute a fixed amount every month for irregular annual costs like insurance or gifts — set it when creating a bucket, or add it later by editing one.",
    "Recurring now has an Audit view, sorted by true monthly cost across every cadence, with a Keep / Reviewing / Canceled status you can set per item — canceling is just a label and still counts until you actually delete it.",
    "A new Household tab shows spending, income, and net worth broken down by family member, plus a per-person cut of this month's budget (budgets themselves are still shared per category, not per-person).",
    "Budget categories can now opt into a stricter 90% warning threshold instead of the default 80%, via a \"Cap\" checkbox on each row.",
    "Settings has a new \"Feature toggles\" section — turn Apply to Debt, Split purchases, or Envelope Caps off to hide them everywhere they appear; nothing already stored is lost, and turning a feature back on picks up right where it left off.",
  ],
  "1.2.2": [
    "Buckets can now be color-coded — pick a color when creating or editing one, and it carries through to that bucket's card and the new \"Buckets overview\" report.",
    "The Dashboard is now customizable: reorder or remove widgets, add report sections pinned from Cash Flow, Investments, and Reports, and switch between Default, Bills Focus, and Investor Focus layouts — or build your own.",
    "Two new reports: \"Buckets overview\" (every bucket's progress at a glance) and \"Savings rate trend\" (income minus expenses, as a percentage, charted by month).",
    "Two new visual themes in Settings ▸ Appearance, alongside Classic: Aurora (navy with lavender, mint, and coral) and Midnight Emerald (slate and emerald). Both are dark-only, so the sidebar's Light/Dark/System toggle steps aside while one is active.",
    "A new \"Ask your ledger\" box on the Dashboard answers questions typed in plain English — spending by category or merchant over a time period, runway what-ifs, account/net worth/debt lookups, subscription totals, bucket progress, savings rate, and month-over-month comparisons — computed entirely from your own local data, never sent anywhere.",
    "Fixed: the Dashboard's Debt tile could show red even while a debt was actively being paid down. It now tracks the actual amount owed, so paying down debt shows green with a downward trend line, and only rising debt shows red.",
  ],
  "1.2.3": [
    "A fourth visual theme, Futuristic, joins Aurora and Midnight Emerald in Settings ▸ Appearance — a neon cyberpunk look with electric cyan, violet, and magenta-red accents, plus Orbitron and Share Tech Mono type. Unlike the other two reskins, Futuristic has a light mode as well as dark, and follows the sidebar's Light/Dark/System toggle.",
    "Futuristic also swaps in its own angular, HUD-style sidebar icon set in place of the app's default icons.",
    "New icons throughout the app: categories, account types, and budget groups now show a small icon next to their name on the Dashboard, Ledger, Recurring, Accounts, and Budget tabs.",
    "The Dashboard's Insights feed now calls out good news too, not just warnings — a category you meaningfully cut back on shows up as a positive \"nice work\" callout.",
    "Investments: click \"Total gain/loss\" or \"Today's gain/loss\" to see exactly which holdings are driving that number — the same \"what makes up this\" breakdown the Dashboard and Accounts tabs already use for their stat tiles.",
    "Accounts' stat tiles (Total Assets, Total Liabilities, Net Worth) can now be clicked for a \"what changed\" breakdown, same as the Dashboard.",
    "Ledger: tag several selected transactions at once, alongside the existing bulk category correction.",
    "Budget categories can now be reordered with ↑/↓ buttons next to each row, not just by dragging.",
    "Household's spending and income by person are now scoped to the month you're viewing, matching the budget-by-person card below them.",
    "Dialogs (Add account, Edit transaction, etc.) now trap keyboard focus while open — Tab cycles within the dialog instead of escaping to the page behind it — and restore focus to what you were on when closed.",
    "Renamed the Dashboard's natural-language question box from \"Ask your ledger\" to \"Ask the Vault,\" with a new icon, randomized example questions, and a \"Tips & examples\" guide for phrasing questions it can actually answer.",
    "Faster Ledger, Budget, and Reports screens on large datasets, from new database indexes and less redundant recalculation.",
    "Fixed: a single unusually large one-off expense in a brand-new category could trigger a false \"on pace to exceed budget\" warning even with no spending history to project from.",
    "Fixed: the new account dialog could occasionally leave its name field unfocused when opened.",
    "Fixed: \"what's my savings rate this month\" and similar bare time-period questions weren't recognized by Ask the Vault.",
  ],
  "1.2.4": [
    "A new visual theme, Slate, replaces Classic as Vault Spend's default look — a refreshed palette, typography, and iconography. Aurora and Midnight Emerald have been retired; Futuristic remains as the other option.",
    "Every tab now has its own page header with a title and description, and the Light/Dark/System toggle has moved from the sidebar footer to the top header.",
    "\"Buckets\" is now called \"Goals\" throughout the app.",
    "Goals can now have a custom icon, in addition to the existing color.",
    "The Dashboard has a new Quick actions row (Add transaction, Add account, Set budget, Update goals), and \"+ Add widget…\" can now pin one specific account, goal, or investment account, not just a fixed catalog widget.",
    "Pinned account/goal/investment widgets on the Dashboard now match the look of the main Net Worth/Cash/Debt/Investments cards, with an icon badge and colored background.",
    "Customize your Dashboard layout, then save and name your own arrangement — it's kept alongside the Default/Bills Focus/Investor Focus presets, so you can switch back to it (or delete it) any time.",
    "Fixed: Reports' \"Income (all-time)\" stat, the Savings Rate Trend, Ask the Vault, and Household's income-by-person could all read $0 or an incorrect total for a paycheck not categorized literally \"Income\" (e.g. \"Salary\") — income is now calculated the same consistent way everywhere, matching Cash Flow.",
    "Fixed: a credit card or loan payment (or an escrow refund) could inflate reported income.",
    "Fixed: investment holdings weren't counting toward Net Worth, Accounts, and Household totals.",
    "Fixed: a Budget category's name could be cut down to a single letter once it showed a budget-alert badge.",
    "Fixed: a goal's contribution amount field showed a cut-off placeholder instead of the full \"Amount (negative = withdrawal)\".",
    "Fixed: low-contrast button and active-nav text in the Slate theme's light mode.",
    "This dialog is wider, so a full release's notes read as normal paragraphs instead of a cramped, scrolled column.",
  ],
  "1.2.5": [
    "Penny Worth is now Vault Spend — a new name, new tagline (\"Own your Data, Own your Money!\"), and the Dashboard's \"Ask Pennyworth\" box is now \"Ask the Vault.\" Nothing about your data or how the app works has changed.",
    "Settings now has an About section noting Vault Spend is an independent project, not affiliated with any external financial services or wallet providers.",
    "Settings' Icon credits is now a collapsed section you can expand, instead of a long list shown by default.",
    "Fixed: a loan account's balance worked backwards from how a credit card's does — a positive transaction increased what you owed, and a negative one paid it down. Loans now match credit cards: a payment is entered as a positive amount and reduces what's owed; a negative amount represents new borrowing. Existing loan transactions were automatically converted to the new convention, with no change to any account's tracked balance.",
    "A transaction recorded directly on a loan account (a mortgage payment, say) can now \"Split principal →\" to specify that only part of it — not the whole payment — counts toward what's owed, the same way \"Apply to a debt\" already let you do for a payment made from a different account.",
    "Adding a transaction dated on or before an account's last balance correction or monthly rollover now shows a warning that it won't change today's balance, so it isn't a silent surprise — the transaction still correctly affects past balance history.",
    "\"Ledger\" is now called \"Transactions\" throughout the app.",
    "Accounts and categories now have an icon picker, just like Goals already did — pick an explicit icon when creating one, or change it later (click an account's icon on the Accounts page, or a category's icon in Manage categories). Leaving it unset keeps the automatic guess based on the account type or category name. Also added a set of full-color icons for common categories (groceries, restaurants, shopping, travel, and more), account types, a new \"car\" Goal icon, the Dashboard's Net Worth/Cash/Debt cards, and the warning triangle shown for over-budget alerts.",
    "Profiles can now have an icon too — pick one of 15 new avatar icons for a profile in Settings' Profiles section, shown there and in the sidebar's profile switcher.",
  ],
  "1.2.6": [
    "Added a third visual theme, Transparent — a frosted-glass look with translucent blurred panels, a color wash behind the sidebar and toolbar, pill-shaped buttons, and a soft glass highlight behind the active nav item. Pick it from Settings > Appearance, alongside Slate and Futuristic.",
    "Fixed a white box behind the app icon — its rounded corners had an opaque near-white fill instead of transparency, so a light square showed through around it on dark backgrounds like the Windows taskbar.",
    "Fixed: a category that arrived only through a file import's own \"Category\" column (a bank's CSV export, say) could show up on the transaction itself but never appear in the \"All categories\" filter or Manage categories. It's now registered the moment it's imported, and any category already stuck in this state from an earlier import is picked up automatically the next time you open the app.",
    "Fixed a credit card with no limit set showing a confusing negative \"Available\" figure — it now prompts you to set a credit limit instead.",
    "Fixed stat cards on Recurring, Budget, and Accounts clipping large dollar amounts (a six- or seven-figure balance, say) instead of fitting or wrapping onto a second line.",
    "Cash Flow now opens to a 3-month view by default instead of 6, so a newer account isn't greeted with a mostly-empty chart.",
    "Fixed the Transactions table — and Budget's category rows — dragging the whole page sideways when a column ran wide; scrolling now stays scoped to just the table or row that needs it.",
  ],
  "1.2.7": [
    "Investment accounts now show where they're headed. A Roth IRA, 529 or brokerage account's Details page tracks the cash you've put in, what it's worth today, and a projected balance at a withdraw month you choose — with an assumed return, an optional spread of withdrawals over several years, and a today's-dollars switch. The Investments tab gets an \"Accumulation & projection\" table and chart covering every account.",
    "Transfers between your own accounts — a \"Transfer\" category, or two matching transactions you link — no longer count as spending or income, and the two sides of a transfer show as one row once linked. Turn on \"Link matching transfers automatically\" in Settings > Feature toggles to link clear-cut pairs after every import, then check them in the review list — Unlink any you disagree with and it won't be linked again.",
    "The Dashboard's \"Safe to spend\" shows what's left of your cash after the Recurring bills due before your next paycheck, and Cash Flow's Forecast now counts those bills on their due dates. \"Needs a look\" opens with a To do list: uncategorized transactions, bills due soon, Recurring bills that look missed or changed price, and a finished month waiting for its review.",
    "Budget can suggest an amount for each category from your last 3 months, shows what's unallocated from your income and how far through the month you are, and can roll a category's unspent money into next month. A new Month-end review walks through a finished month. Goals show a projected finish date and what they need per month, and a goal can follow an account's balance.",
    "Categorization rules are now managed in Settings, and after you fix a transaction's category Vault Spend offers to apply the same fix to similar ones. After an import, a Review inbox lists anything worth a second look — uncategorized, a low-confidence guess, a possible duplicate or an unusually large charge.",
    "Reports has a Sankey diagram of your income flowing to spending and a daily-spending heatmap, and the tab was rebuilt around them. Property & Valuables and account balances now live on the Accounts tab, and the setup-data import/export is in Settings.",
    "Accounts have their own Details page with a balance-history chart and Reconcile for checking a statement's ending balance. Investments add a portfolio value history and a Target allocation by asset class.",
    "Transactions show compact rows by default, editing an account happens in one Edit dialog, and Recurring bills are matched against your transactions — a bill that looks missed or changed price is called out.",
    "A Hide amounts button covers every dollar figure with •••• (it can also do it when the window loses focus), Ctrl+K opens a command palette that jumps to any tab, account, goal or transaction, and Settings can keep Vault Spend in the system tray so bill reminders arrive with the window closed.",
    "Backups can be copied to a second folder automatically, so one failed disk can't take your data and its backups with it.",
    "Fixed: a monthly \"Transfer to Savings\" showed up as spending on the Dashboard, in Cash Flow's top categories and merchants, in Recurring's Suggested list and in your runway estimate.",
    "Fixed: the sortable headings on Transactions couldn't be reached with the keyboard or announced by a screen reader — they can now. The new projection charts can also be read with the arrow keys, not only with the mouse.",
    "Fixed: toasts were see-through in the Transparent theme, which made them hard to read over busy content.",
  ],
};
