// Generated by tools/generate_mobile_snapshot_types.py; do not edit.

export type Label = string;
export type OpaqueId = string;
export type Decimal = string;
export type Sequence = string;
export type Date = string;
export type Month = string;
export type UtcTimestamp = string;
export interface Availability {
  state: "available" | "partial" | "unavailable";
  reason: Label | null;
}
export interface Sections {
  overview: Availability;
  accounts: Availability;
  investments: Availability;
  budgets: Availability;
  reports: Availability;
  comparisons: Availability;
  calculators: Availability;
}
export interface Profile {
  id: OpaqueId;
  name: Label;
  icon: Label | null;
}
export interface Overview {
  netWorth: Decimal;
  cash: Decimal;
  debtContribution: Decimal;
  investments: Decimal;
  otherAccounts: Decimal;
  propertyValue: Decimal;
  propertyValuedFrom: Date | null;
  propertyValuedThrough: Date | null;
  averageMonthlySpend: Decimal | null;
  runwayMonths: Decimal | null;
}
export interface Account {
  id: OpaqueId;
  name: Label;
  accountType: "checking" | "savings" | "credit" | "loan" | "investment" | "other";
  balance: Decimal;
  startingBalance: Decimal;
  netWorthContribution: Decimal;
  owed: Decimal | null;
  balanceBasis: "ledger" | "holdings";
  checkpointDate: Date | null;
  memberId: OpaqueId | null;
  icon: Label | null;
}
export interface Member {
  id: OpaqueId;
  name: Label;
}
export interface QuoteCoverage {
  state: "complete" | "partial" | "unavailable";
  valuedPositions: number;
  totalPositions: number;
  quoteTimestamp: UtcTimestamp | null;
  previousCloseDate: Date | null;
}
export interface InvestmentSummary {
  accountId: OpaqueId;
  value: Decimal;
  costBasis: Decimal | null;
  unrealizedGain: Decimal | null;
  dayChange: Decimal | null;
  coverage: QuoteCoverage;
}
export interface Investments {
  value: Decimal;
  costBasis: Decimal | null;
  unrealizedGain: Decimal | null;
  dayChange: Decimal | null;
  coverage: QuoteCoverage;
  accounts: (InvestmentSummary)[];
}
export interface BudgetLine {
  category: Label;
  group: "income" | "fixed" | "flexible" | "nonmonthly";
  order: number;
  planned: Decimal;
  actual: Decimal;
  rollover: Decimal;
  effectiveBudget: Decimal;
  remaining: Decimal;
  capEnabled: boolean;
  rolloverEnabled: boolean;
  alert: "none" | "warning" | "over";
}
export interface BudgetMonth {
  month: Month;
  actualThrough: Date | null;
  sourceMonth: Month | null;
  capFeatureEnabled: boolean;
  rolloverFeatureEnabled: boolean;
  lines: (BudgetLine)[];
  unbudgetedSpending: Decimal;
  actualIncome: Decimal;
  actualSpending: Decimal;
}
export interface MonthTotals {
  month: Month;
  income: Decimal;
  spending: Decimal;
  savingsRatePct: Decimal | null;
}
export interface CategoryMonth {
  month: Month;
  category: Label;
  group: "income" | "fixed" | "flexible" | "nonmonthly" | null;
  spending: Decimal;
}
export interface BudgetCategoryMonth {
  month: Month;
  category: Label;
  signedAmount: Decimal;
}
export interface DailySpend {
  date: Date;
  spending: Decimal;
}
export interface MonthBreakdown {
  month: Month;
  id: OpaqueId | null;
  label: Label;
  income: Decimal;
  spending: Decimal;
}
export interface NetWorthPoint {
  date: Date;
  netWorth: Decimal;
  cash: Decimal;
  debtContribution: Decimal;
  investments: Decimal;
  propertyValue: Decimal;
  valuationBasis: "current_saved_values" | "recorded";
}
export interface ValuePoint {
  date: Date;
  value: Decimal;
}
export interface MemberWorth {
  memberId: OpaqueId | null;
  label: Label;
  value: Decimal;
}
export interface History {
  fromMonth: Month | null;
  throughMonth: Month | null;
  actualThrough: Date;
  months: (MonthTotals)[];
  categories: (CategoryMonth)[];
  budgetCategoryNet: (BudgetCategoryMonth)[];
  daily: (DailySpend)[];
  accounts: (MonthBreakdown)[];
  members: (MonthBreakdown)[];
  tags: (MonthBreakdown)[];
  merchants: (MonthBreakdown)[];
  netWorth: (NetWorthPoint)[];
  portfolio: (ValuePoint)[];
  memberNetWorth: (MemberWorth)[];
}
export interface DollarBasis {
  kind: "month" | "annual_average";
  period: Label;
}
export interface ComparisonReference {
  id: Label;
  mode: "household" | "individual";
  definitionId: Label;
  value: Decimal;
  adjustedValue: Decimal;
  uncertainty: Decimal | null;
  uncertaintyKind: "moe90" | "se" | null;
  unit: "usd_per_year" | "usd_per_month" | "usd_balance";
  statistic: "mean" | "median";
  population: Label;
  universe: "all" | "holders";
  geography: Label;
  ageMin: number;
  ageMax: number | null;
  periodKind: "flow" | "stock";
  periodFrom: Date;
  periodTo: Date;
  dollarBasis: DollarBasis;
  adjustedBasisMonth: Month;
  cpiFactor: Decimal;
  sourceId: Label;
  sourceUrl: Label;
  sourceLocator: Label;
  annotation: Label | null;
  reliability: "ok" | "unreliable";
}
export interface ComparisonReason {
  code: Label;
  detail: Label | null;
  options: (Label)[];
}
export interface ComparisonResult {
  metric: "spending" | "investments" | "income" | "savings" | "debt";
  status: "comparable" | "approximate" | "missing_input" | "incomplete" | "unavailable" | "unreliable" | "cohort_choice_required" | "not_comparable";
  localValue: Decimal | null;
  reference: ComparisonReference | null;
  dollarDifference: Decimal | null;
  percentDifference: Decimal | null;
  completeness: "confirmed" | "partial" | "unknown";
  reasons: (ComparisonReason)[];
}
export interface ComparisonContributor {
  label: Label;
  gross: Decimal;
  shareBasisPoints: number;
  counted: Decimal;
}
export interface ComparisonClass {
  label: Label;
  value: Decimal;
}
export interface ComparisonSecondary {
  label: Label;
  result: ComparisonResult;
}
export interface ComparisonCard {
  result: ComparisonResult;
  visible: boolean;
  definitionId: Label | null;
  stale: boolean;
  personalIncomeHint: boolean;
  metricUnit: "usd_per_year" | "usd_per_month" | "usd_balance";
  periodKind: "flow" | "stock" | null;
  periodFrom: Date | null;
  periodTo: Date | null;
  origin: "derived" | "entered";
  measuredOn: Date | null;
  explanation: Label | null;
  unallocated: Decimal;
  trackedValue: Decimal | null;
  contributors: (ComparisonContributor)[];
  excluded: (ComparisonReason)[];
  classTotals: (ComparisonClass)[];
  notes: (ComparisonReason)[];
  secondary: (ComparisonSecondary)[];
}
export interface Comparisons {
  configured: boolean;
  packageVersion: Label | null;
  setupRevision: Sequence;
  problem: Label | null;
  cards: (ComparisonCard)[];
}
export interface ContributionMonth {
  month: Month;
  moneyIn: Decimal;
  moneyOut: Decimal;
}
export interface AccumulationPlan {
  monthlyContribution: Decimal | null;
  annualReturnPct: Decimal;
  withdrawMonth: Month | null;
  withdrawYears: number | null;
}
export interface Accumulation {
  accountId: OpaqueId;
  months: (ContributionMonth)[];
  totalIn: Decimal;
  totalOut: Decimal;
  net: Decimal;
  firstDeposit: Date | null;
  depositCount: number;
  plan: AccumulationPlan;
  valueHistory: (ValuePoint)[];
}
export interface DebtInput {
  accountId: OpaqueId;
  owed: Decimal;
  annualRatePct: Decimal | null;
  excluded: boolean;
}
export interface ScheduledFlow {
  date: Date;
  moneyIn: Decimal;
  moneyOut: Decimal;
}
export interface Forecast {
  throughDate: Date;
  startBalance: Decimal;
  trendDailyNet: Decimal;
  everydayDailyNet: Decimal;
  usesRecurring: boolean;
  schedule: (ScheduledFlow)[];
}
export interface GoalSummary {
  id: OpaqueId;
  name: Label;
  target: Decimal | null;
  saved: Decimal;
  targetDate: Date | null;
  monthlyContribution: Decimal | null;
  monthlyPace: Decimal;
  tracksAccount: boolean;
  linkedAccountId: OpaqueId | null;
  memberId: OpaqueId | null;
}
export interface RecurringSummary {
  monthlyIncome: Decimal;
  monthlyExpense: Decimal;
  annualIncome: Decimal;
  annualExpense: Decimal;
}
export interface Calculators {
  inflationPct: Decimal;
  accumulation: (Accumulation)[];
  debts: (DebtInput)[];
  forecast: Forecast;
  goals: (GoalSummary)[];
  recurring: RecurringSummary;
}
export interface MobileSnapshotV1 {
  schemaVersion: 1;
  minimumViewerVersion: 1;
  installationId: OpaqueId;
  profile: Profile;
  epoch: OpaqueId;
  sequence: Sequence;
  generatedAt: UtcTimestamp;
  asOfDate: Date;
  currency: "USD";
  sections: Sections;
  members: (Member)[];
  overview: Overview;
  accounts: (Account)[];
  investments: Investments;
  budgets: (BudgetMonth)[];
  history: History;
  comparisons: Comparisons;
  calculators: Calculators;
}
