import { useEffect, useState } from "react";
import { QRCodeSVG } from "qrcode.react";
import { ModalShell } from "./Modal";
import { MenuSelect } from "./MenuSelect";
import { errorMessage } from "./errorMessage";
export interface MobileSetupInfo { url:string;expires:number }
interface Props {
 origin:string|null; fingerprint:string|null; networks:{value:string;label:string}[];
 network:string;onNetwork:(value:string)=>void;
 onEnable:()=>Promise<void>;onBegin:()=>Promise<MobileSetupInfo>;
 onCancelSetup:()=>Promise<void>;onExport:()=>Promise<void>;onPair:()=>Promise<void>;onClose:()=>void;
}
export function MobileSetupWizard(p:Props){
 const [phone,setPhone]=useState("iphone"),[step,setStep]=useState(0),[setup,setSetup]=useState<MobileSetupInfo|null>(null),[busy,setBusy]=useState(false),[notice,setNotice]=useState(""),[verified,setVerified]=useState(false),[migration,setMigration]=useState(false),[now,setNow]=useState(Date.now());
 const migrating=!!p.origin&&!p.origin.includes(".local:");
 const run=async(action:()=>Promise<void>)=>{if(busy)return;setBusy(true);setNotice("");try{await action();}catch(error){setNotice(errorMessage(error));}finally{setBusy(false);}};
 useEffect(()=>{const timer=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(timer);},[]);
 const expired=!!setup&&setup.expires*1000<=now;
 const next=()=>{setVerified(false);setStep(step+1);};
 const close=()=>void run(async()=>{await p.onCancelSetup();p.onClose();});
 const ios=phone==="iphone";
 const steps=[
  {device:"computer",title:"Take your balances with you",body:<><p>You will set this up once on your computer and phone. Your financial snapshots stay on your devices.</p><p>You will install a small certificate on your phone. It helps the browser recognize this computer. Phone Settings will ask you to confirm it.</p><MenuSelect ariaLabel="Your phone" value={phone} onChange={setPhone} options={[{value:"iphone",label:"iPhone"},{value:"android",label:"Android"}]} fill/><p>You need your phone, your home Wi-Fi and Vault Spend open on this computer.</p></>,action:next,label:"Let’s get started",help:"No mobile app or online account is needed. This certificate trusts certificates signed by this installation. Remove it in phone Settings when you stop using mobile access."},
  {device:"phone",title:"Join the same home network",body:<><p>On your phone, open Settings and check that it uses your home Wi-Fi.</p><p>Your computer can use a cable to the same router. Keep this computer awake with Vault Spend open.</p></>,action:next,label:"My phone is on the home Wi-Fi",help:"Avoid guest Wi-Fi, which may keep devices apart. Do not change router settings or turn off protection to continue."},
  {device:"computer",title:"Enable your local connection",body:<><p>Check the network below. This is where your phone will connect.</p><MenuSelect ariaLabel="Setup home network" value={p.network} onChange={p.onNetwork} options={p.networks} disabled={busy} fill/><p>The viewer will use a stable local name. This avoids needing to reserve an address in your router on networks where local name discovery works.</p>{migrating&&<><p className="mobile-setup-warning">Your existing viewer uses an IP address. The new local name is a different browser storage location. Old saved copies stay at the old address; pair and save again at the new one.</p><label className="mobile-setup-check"><input type="checkbox" checked={migration} onChange={e=>setMigration(e.target.checked)}/>I understand that existing phones must pair and download again at the new address.</label></>}</>,action:()=>void run(async()=>{await p.onEnable();setSetup(await p.onBegin());next();}),label:"Enable and show setup code",disabled:!p.network||(migrating&&!migration),help:"If there are several networks, choose the private home connection used by your phone. A firewall prompt may require permission for this app’s private-network connection. Do not allow all-network access."},
  {device:"phone",title:"Scan to open phone instructions",body:<><p>Open your phone Camera and point it at this code. Tap the link that appears.</p>{setup&&!expired?<div className="mobile-desktop-pair"><QRCodeSVG value={setup.url} size={208} marginSize={4} title="Temporary certificate-only phone setup link"/><p>Setup code expires in {Math.max(0,Math.ceil((setup.expires*1000-now)/1000))} seconds.</p></div>:<p role="status">This setup code expired. Show a new one to continue.</p>}<button className="modal-secondary" disabled={busy} onClick={()=>void run(async()=>setSetup(await p.onBegin()))}>Show a new setup code</button><p>The phone page offers a public certificate download and instructions only. It cannot show finances or grant profile access.</p></>,action:next,label:"The phone setup page is open",disabled:expired,help:"Move the phone back a little so the whole code is visible. Keep both devices on the same home network. If the setup link cannot open, check the private-network firewall permission."},
  {device:"phone",title:"Download and verify the certificate",body:<><p>On the phone page, choose your phone type and tap Download certificate.</p><p>Before installing, compare the actual certificate’s full SHA-256 fingerprint with the number below. The file’s name or text on the download page is not enough.</p><p className="mobile-desktop-code">{p.fingerprint??"Certificate fingerprint unavailable."}</p><p className="mobile-setup-warning">If your phone cannot show the actual certificate fingerprint, pause. Use Export public certificate on this computer and a direct transfer you control, such as a cable, instead.</p><button className="modal-secondary" disabled={busy} onClick={()=>void run(p.onExport)}>Export certificate for direct transfer</button><label className="mobile-setup-check"><input type="checkbox" checked={verified} onChange={e=>setVerified(e.target.checked)}/>I verified the actual certificate, or transferred it directly from this computer using a trusted method.</label></>,action:next,label:"The certificate is verified",disabled:!verified||!p.fingerprint,help:"A downloaded certificate is not automatically trusted. Do not install it if the fingerprint differs. The temporary HTTP page is only a delivery mechanism and cannot prove the certificate’s identity."},
  {device:"phone",title:ios?"Open Profile Downloaded":"Find CA certificate installation",body:ios?<><p>Leave the browser and open iPhone Settings.</p><p>Tap Profile Downloaded near the top. Check that it is the verified Vault Spend certificate profile.</p><p>Tap Install in the upper-right corner and follow the phone’s prompts. Enter any phone passcode only in Settings, never in the website.</p></>:<><p>Open Android Settings. Look under Security → Encryption &amp; credentials → Install a certificate → CA certificate.</p><p>Select the verified vault-spend-local-root.crt file from Downloads and follow the phone’s prompts.</p><p>Menu names vary by phone. Search Settings for “certificate” or “credentials” if needed.</p></>,action:next,label:"The certificate is installed",help:ios?"If Profile Downloaded is missing, download again and open Settings promptly. An uninstalled downloaded profile expires after eight minutes. If device management blocks installation, pause rather than changing management or security settings.":"Choose the CA certificate option, not a Wi-Fi client certificate. If device management blocks installation, pause and record the message rather than changing protection settings."},
  ...(ios?[{device:"phone",title:"Turn on browser trust",body:<><p>In iPhone Settings, open General → About → Certificate Trust Settings.</p><p>Under Enable full trust for root certificates, enable the verified Vault Spend local certificate. Confirm the phone’s prompt.</p></>,action:next,label:"Trust is turned on",help:"If the Vault Spend switch is missing, check that you installed the profile. Downloading it by itself is not enough."}]:[]),
  {device:"phone",title:"Return to the secure viewer",body:<><p>Return to the phone’s setup tab and tap Open secure viewer.</p><p>It must open without a certificate warning. If a warning appears, return to the certificate steps; do not bypass it.</p>{p.origin&&<p className="mobile-desktop-code">{p.origin}/mobile/</p>}<p>If you want a home-screen shortcut, add and open it before pairing. Its storage may be separate from your browser tab.</p></>,action:next,label:"The viewer opened without a warning",help:"If the local name does not resolve, check the network and any VPN. Some networks block local discovery. Use the connection details in Settings for troubleshooting; changing to an IP address creates a separate saved-data location."},
  {device:"computer",title:"Pair and approve this phone",body:<><p>Choose Create pairing QR below. This closes the guide and shows a fresh pairing code on this computer.</p><p>Scan it using the phone context you plan to use, or paste the code into your home-screen viewer. Request access on the phone.</p><p>Vault Spend will ask you to approve the phone and choose its profiles. After approval, return to the phone and wait for the saved snapshot and Ready offline.</p><p>For a fresh copy later, keep this app open with the requested profile active and unlocked. Away from home, the phone shows its last saved copy.</p></>,action:()=>void run(async()=>{await p.onCancelSetup();await p.onPair();p.onClose();}),label:"Create pairing QR",help:"Certificate trust and profile approval are separate steps. You can revoke future access here later; it cannot erase a phone’s already saved offline copy."}
 ];
 const current=steps[Math.min(step,steps.length-1)];
 return <ModalShell title="Set up your phone" onCancel={close} headerAction={<button className="modal-secondary" disabled={busy} onClick={close}>Close guide</button>} footer={<div className="modal-actions mobile-setup-actions"><button className="modal-secondary" disabled={busy||step===0} onClick={()=>{setVerified(false);setStep(step-1);}}>Back</button><button disabled={busy||current.disabled} onClick={current.action}>{busy?"Please wait…":current.label}</button></div>}>
 <div className="mobile-setup-wizard"><p className="mobile-setup-device">On your {current.device}</p><p>Step {step+1} of {steps.length}</p><h3>{current.title}</h3>{current.body}<details><summary>I need help with this step</summary><p>{current.help}</p></details>{notice&&<p role="alert">{notice}</p>}</div>
 </ModalShell>;
}
